config/routes.rb
Tony612Com::Application.routes.draw do

  resources :posts
  root to: "posts#index"
  get "login" => 'sessions#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions/destroy' => 'sessions#destroy', as: 'destroy_sessions'

  # FIXME: warden doesn't need this route. But test needs.
  get 'unauthenticated' => 'sessions#unauthenticated'
end

app/models/concerns/markdown.rb
module Markdown
  extend ActiveSupport::Concern

  def markdown(text, index = false)
    pygments_style = HTMLwithPygments.new(:filter_html => true, :hard_wrap => true, :gh_blockcode => true)
    options = {
      :autolink => true,
      #:space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :strikethrough =>true,
      :lax_html_blocks => true,
      :superscript => true
    }
    options[:fenced_code_blocks] = false if index
    #markdown = Redcarpet::Markdown.new(coderayified,options)
    markdown = Redcarpet::Markdown.new(pygments_style, options)
    markdown.render(text).html_safe
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants
    def block_code(code ,language)
      Pygments.highlight(code, :lexer => language || "ruby", :options => {:encoding => 'utf-8'})
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string(255)      not null
#  content          :text             not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  category         :string(255)
#  excerpt          :text
#  excerpt_markdown :text
#  markdown_html    :text
#

class Post < ActiveRecord::Base

  validates_presence_of :title, :content

  scope :order_by_time, -> { order("created_at DESC") }
  scope :life, -> { where(category: "life").order_by_time }
  scope :tech, -> { where(category: "tech").order_by_time }

  include Markdown

  def to_param
    "#{id}-#{title_url}"
  end

  def title_url
    title.parameterize
  end

  before_save :generate_markdown_html
  def generate_markdown_html
    self.markdown_html = markdown(content || "")
    self.excerpt_markdown = markdown(excerpt || "")
  end
end

app/models/user.rb
class User
  def self.find_from_user_info(user_info=['', ''])
    return nil unless user_info.is_a?(Array)
    username, email = user_info
    id_str = username + ':' + email
    return user_info if id_str == ENV['GITHUB_ADMIN_ID']
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_admin!
    redirect_to login_path, alert: "Please sign in first" unless admin_signed_in?
  end

  def user_signed_in?
    warden.authenticated?
  end
  helper_method :user_signed_in?

  def admin_signed_in?
    user_signed_in? && User.find_from_user_info(warden.user)
  end
  helper_method :admin_signed_in?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json
  respond_to :atom, :rss, only: :index

  before_action :authenticate_admin!, :only => [:new, :create, :edit, :update, :destroy]

  layout "post_show", only: [:show, :new, :edit]

  def index
    @posts = Post.order_by_time.page(params[:page]).per(5)

    respond_with @posts
  end

  def show
    @post = Post.find(params[:id])

    respond_with @post
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render action: 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :created_at, :category, :excerpt)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  def new
    redirect_to '/auth/github'
  end

  def create
    warden.authenticate!(:github)
    redirect_to '/', notice: "Authing successful"
  end

  def unauthenticated
    logger.debug "Unauthenticated"
    redirect_to '/', alert: "Unauthenticated!"
  end

  def destroy
    warden.logout
    redirect_to '/', notice: "Logged out"
  end

  protected

  def warden
    request.env['warden']
  end

  def require_no_authentication
    redirect_to root_path if admin_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_sidebar.html.slim
.photo
  = gravatar_image_tag "h.bing612@gmail.com"
.profile
  p How far your heart goes
  p how far you will

.social-links
  = link_to "https://github.com/tony612", target: '_blank' do
    i.fa.fa-github.fa-lg
  = link_to "https://twitter.com/tony612_han", target: '_blank' do
    i.fa.fa-twitter.fa-lg
  = mail_to "h.bing612@gmail.com", target: '_blank' do
    i.fa.fa-envelope.fa-lg
  = link_to posts_path(format: :atom), target: '_blank' do
    i.fa.fa-rss.fa-lg

.admin
  - if admin_signed_in?
    = link_to new_post_path do
      i.fa.fa-pencil-square-o
    = link_to destroy_sessions_path, :method => :delete do
      i.fa.fa-sign-out

app/views/layouts/application.html.slim
doctype 5
| <!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
| <!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
| <!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
| <!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
| <!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->

html
  head
    title Tony612

    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield :auto_discovery_feed
  body#top
    .legend
      h1 Tony.blogs
    #sidebar.expanded
      = render "layouts/sidebar"

    .main
      p.notice = notice
      p.alert = alert
      = yield
      p#back-top
        a href="#top"
          span.fa-stack.fa-2x
            i.fa.fa-square.fa-stack-2x
            i.fa.fa-arrow-up.fa-stack-1x.fa-inverse

/[if lt IE 7 ]
  = javascript_include_tag '/javascripts/dd_belatedpng.js'
  = javascript_tag 'DD_belatedPNG.fix("img, .png_bg");'

| </html>

app/views/layouts/post_show.html.slim
doctype 5
| <!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
| <!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
| <!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
| <!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
| <!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->

html
  head
    title
      = "Tony612 - #{@post.title}"

    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield :auto_discovery_feed
  body
    .go-home
      = link_to root_path do
        span.fa-stack.fa-lg
          i.fa.fa-circle.fa-stack-2x
          i.fa.fa-home.fa-stack-1x.fa-inverse
    .main-post
      - if notice
        p.notice = notice
      - if alert
        p.alert = alert
      = yield

/[if lt IE 7 ]
  = javascript_include_tag '/javascripts/dd_belatedpng.js'
  = javascript_tag 'DD_belatedPNG.fix("img, .png_bg");'

| </html>

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.input :title, label: false
  = f.input :category, label: false, collection: ["life", "tech"]
  = f.input :content, label: false, input_html: {style:"width: 700px;height: 1000px;"}
  = f.label :excerpt
  = f.input :excerpt, label: false, input_html: {style:"width: 700px;height: 400px;"}
  = f.input :created_at, label: false
  = f.submit

app/views/posts/_post.html.slim
- cache ["list", post, admin_signed_in?] do
  li
    .title
      h1
        = link_to post.title, post
    .info
      = post.created_at.to_date.strftime('%b %e, %Y')
      '
      - if admin_signed_in?
        = link_to "edit", edit_post_path(post)
        | &nbsp;
        = link_to "delete", post_path(post), :method => :delete

    .content
      = raw (post.excerpt_markdown || post.markdown_html[0..500])

app/views/posts/edit.html.slim
h1 Edit Post

== render "form"

app/views/posts/index.html.slim
- content_for :auto_discovery_feed do
  = auto_discovery_link_tag :atom, posts_url(format: :atom)
  = auto_discovery_link_tag :rss, posts_url(format: :rss)

- cache [@posts, admin_signed_in?] do
  ul.posts
    = render partial: "post", collection: @posts

  = paginate @posts

app/views/posts/new.html.slim
h1 New Post

== render "form"

app/views/posts/show.html.slim
- cache [@post, admin_signed_in?] do
  #post
    h1.title = @post.title

    .info
      = @post.created_at.to_date.to_formatted_s(:long_ordinal)
      '
      - if admin_signed_in?
        = link_to "edit", edit_post_path(@post)
        | &nbsp;
        = link_to "delete", post_path(@post), :method => :delete

    .article
      = raw @post.markdown_html || ""

  #disqus_thread

    script
      | var disqus_shortname = 'tony612';
      | (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                      dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                                                      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                                                                  })();
    noscript
      | Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>